apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atlas-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atlas
spec:
  selector:
    matchLabels:
      app: atlas
  replicas: 1
  serviceName: atlas
  template:
    metadata:
      labels:
        app: atlas
    spec:
      containers:
        - name: atlas
          image: sburn/apache-atlas
          ports:
            - containerPort: 21000
            - containerPort: 2181
            - containerPort: 9027
          env:
            - name: ATLAS_SERVER_OPTS
              value: "-Xmx1024m"
          volumeMounts:
            - mountPath: /var/atlas
              name: atlas-data
      volumes:
        - name: atlas-data
          persistentVolumeClaim:
            claimName: atlas-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: atlas
spec:
  type: LoadBalancer  
  selector:
    app: atlas
  ports:
    - name: port-21000
      port: 21000
      targetPort: 21000
      protocol: TCP
    - name: port-2181
      port: 2181
      targetPort: 2181
      protocol: TCP
    - name: port-9027
      port: 9027
      targetPort: 9027
      protocol: TCP
