apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
    name: longtest
    namespace: spark-operator
spec:
    type: Python
    pythonVersion: "3"
    mode: cluster
    image: "quanghuy98/long-test:1.0.2"
    imagePullPolicy: Always
    mainApplicationFile: local:///app/long-test.py
    sparkVersion: "3.3.2"
    restartPolicy:
        type: OnFailure
        onFailureRetries: 3
        onFailureRetryInterval: 10
        onSubmissionFailureRetries: 5
        onSubmissionFailureRetryInterval: 20
    driver:
        cores: 2
        memory: "1g"
        labels:
            version: 3.3.2
        serviceAccount: my-release-spark
        env: # cấu hình các biến môi trường (app đọc param từ biến môi trường)
            -   name: AWS_REGION
                value: us-east-1
            -   name: AWS_ACCESS_KEY_ID
                value: rafflesit
            -   name: AWS_SECRET_ACCESS_KEY
                value: rafflesit
            -   name: ETL_DATE
                value: "20220930"
            -   name: ETL_PATH
                value: landing/t24_company
    executor:
        cores: 8
        instances: 4
        memory: "8g"
        labels:
            version: 3.3.2
        env:
            -   name: ETL_DATE
                value: "20220930"
            -   name: ETL_PATH
                value: landing/t24_company
            -   name: AWS_REGION
                valueFrom:
                    secretKeyRef:
                        name: s3-secret
                        key: AWS_REGION
            -   name: AWS_ACCESS_KEY_ID
                valueFrom:
                    secretKeyRef:
                        name: s3-secret
                        key: AWS_ACCESS_KEY_ID
            -   name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                    secretKeyRef:
                        name: s3-secret
                        key: AWS_SECRET_ACCESS_KEY
            -   name: AWS_S3_ENDPOINT
                valueFrom:
                    secretKeyRef:
                        name: s3-secret
                        key: AWS_S3_ENDPOINT
            
