apiVersion: v1
kind: Service
metadata:
  labels:
    app: mypostgres
  name: postgreshive
  namespace: default
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: mypostgres
  type: NodePort
