apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: griffin-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: griffin
spec:
  selector:
    matchLabels:
      app: griffin
  replicas: 1
  serviceName: griffin
  template:
    metadata:
      labels:
        app: griffin
    spec:
      containers:
        - name: griffin
          image: apachegriffin/griffin_spark2:0.4.0
          ports:
            - containerPort: 8080
            - containerPort: 5432
            - containerPort: 8998
            - containerPort: 8088
          volumeMounts:
            - mountPath: /var/griffin
              name: griffin-data
      volumes:
        - name: griffin-data
          persistentVolumeClaim:
            claimName: griffin-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: griffin
spec:
  type: NodePort  
  selector:
    app: griffin
  ports:
    - name: port-8080
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: port-8088
      port: 8088
      targetPort: 8088
      protocol: TCP
    - name: port-5432
      port: 5432
      targetPort: 5432
      protocol: TCP
    - name: port-8998
      port: 8998
      targetPort: 8998
      protocol: TCP

