kind: PersistentVolume 
apiVersion: v1 
metadata: 
  name: dremio-jars-pv 
  labels: 
    type: local 
    app: dremio 
spec: 
  storageClassName: manual 
  capacity: 
    storage: 10Gi 
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: /opt/dremio/jars
---
kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
  name: dremio-jars
  labels: 
    app: dremio 
spec: 
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 8Gi 

