apiVersion: v1
kind: ServiceAccount
metadata:
  name: mage-user

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mage
  name: job-manager
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs", "jobs/status"]
  verbs: ["create", "delete", "get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mage-job-manager
  namespace: mage
subjects:
- kind: ServiceAccount
  name: mage-user # Name of the ServiceAccount
  namespace: mage
roleRef:
  kind: Role # This must be Role or ClusterRole
  name: job-manager # This must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: mage-server
  labels:
    app: mage-server  # Add this label to match the selector in the Service
spec:
  containers:
    - name: mage-server
      image: mageai/mageai:latest
      ports:
        - containerPort: 6789
      volumeMounts:
        - name: mage-fs
          mountPath: /home/src
      env:
        - name: KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
  volumes:
    - name: mage-fs
      hostPath:
        path: /path/to/mage_project
  serviceAccountName: mage-user


---
apiVersion: v1
kind: Service
metadata:
  name: mage-server-service
spec:
  selector:
    app: mage-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 6789
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer

