apiVersion: starrocks.com/v1
kind: StarRocksCluster
metadata:
  name: starrockscluster-sample
  namespace: starrocks
spec:
  starRocksFeSpec:
    image: starrocks/fe-ubuntu:latest
    replicas: 3
    requests:
      cpu: 3
      memory: 4Gi
  starRocksBeSpec:
    image: starrocks/be-ubuntu:latest
    replicas: 3
    requests:
      cpu: 3
      memory: 4Gi