apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ranger-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ranger
spec:
  selector:
    matchLabels:
      app: ranger
  replicas: 1
  serviceName: ranger
  template:
    metadata:
      labels:
        app: ranger
    spec:                            
      containers:
        - name: ranger
          image: apache/ranger:2.4.0
          ports:
            - containerPort: 6080
          env:
            - name: ranger_SERVER_OPTS
              value: "-Xmx1024m"
          volumeMounts:
            - mountPath: /var/ranger
              name: ranger-data
      volumes:
        - name: ranger-data
          persistentVolumeClaim:
            claimName: ranger-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ranger
spec:
  type: LoadBalancer
  selector:
    app: ranger
  ports:
    - port: 6080
      targetPort: 6080
      protocol: TCP
      name: ranger


