apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: open-metadata
  name: openmetadata-dependencies-dags
  labels:
    app: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
